### ISSUE TITLE
should not include `react`/`@react-email/render` as a dependency

### ISSUE THREAD

**Issue by aboubakrbm** [resend/resend-node#309]
This is from `pnpm-lock.yaml`:
```
/resend@3.0.0:
	(...)
	dependencies:
	    '@react-email/render': 0.0.11
```

I don't know why `@react-email/render` is a dependency for `resend` package. If I am using resend in a Nuxt project why should i deal with react-email. I think it would be better if `resend` was an independant package. 

_Originally posted by @aboubakrbm in https://github.com/resend/react-email/issues/1209#issuecomment-1902097701_

**Comment by iBobik** [comment]
Just found I have React in my Nuxt project too :-)

It is nice Resend has this feature, but it should be optional, so we will not have such a huge unnecessary deps.

**Comment by benbrunyee** [comment]
Using Resend in any backend requires React to also be installed????

**Comment by gabrielmfern** [comment]
We've released a canary version that uses `@react-email/render` as an optional peer dependency, which should avoid the problems of installing React or React Email on projects they aren't used.

Here's how to upgrade:
1. Uninstall current version `npm uninstall resend`
2. Install canary version `npm install resend@canary`

And you should be done. The uninstallation is required because just upgrading the version might leave the resolved `@react-email/render` on your lockfile, which means the update wouldn't make any difference. See #555 for more info.

Can anyone test this out and see if it really fixes it for them?

**Comment by gabrielmfern** [comment]
We just released #555 on a stable version [resend@5.0.0](https://github.com/resend/resend-node/releases/tag/v5.0.0).

For those that want to upgrade, run the following (change according to your package manager):
1. `npm uninstall resend`
2. `npm install resend@latest`

This should remove `@react-email/render` from your lockfile safely. If anyone experiences any issues with this, please let me know with a reproduction and I'll reopen.

**Comment by ken717w** [comment]
@gabrielmfern `@react-email/render` isn't mentioned in [Quickstart for Next.js](https://resend.com/docs/send-with-nextjs), took me a while to figure out why. This thread clears things out, I think the docs should be updated if `@react-email/render` is now just a peer dependency.

**Comment by treeder** [comment]
I still get the same error after doing an uninstall then reinstall, on 6.0.1

<img width="701" height="226" alt="Image" src="https://github.com/user-attachments/assets/7022c956-00c2-432f-81e9-b4333ecb1efd" />

**Comment by emiliosheinz** [comment]
@treeder can you provide examples of how you are using the SDK?

**Comment by treeder** [comment]
Just sending emails. I assume that's what this library is for?

**Comment by treeder** [comment]
This is the code:

```js
const resend = new Resend(c.env.RESEND_API_KEY)
  let req = {
    from: opts.from,
    to: opts.to,
    cc: opts.cc,
    subject: opts.subject,
    html: opts.body,
  }
  let rr = await resend.emails.send(req)
```

**Comment by emiliosheinz** [comment]
@treeder, as all the usages of `@react-email/render` are gated under `payload.react`, it is really weird that you are experiencing this issue with the code you shared above.

<img width="1920" height="1079" alt="Image" src="https://github.com/user-attachments/assets/748b490f-e974-4ca5-8107-de6669f8cbef" />

As I can't reproduce the issue myself, would you mind sharing a bit more about your project, environment, and use case? Having more details would really help to find the root cause.

**Comment by emiliosheinz** [comment]
Just realized this happens at build time, I completely overlooked that, sorry about the confusion!

You should be able to fix it by marking `@react-email/render` as external in your bundler config. That way, it won’t try to resolve the package during the build. This won’t hurt your setup because `@react-email/render` import will only happen at runtime if you are actually using React templates, which you aren't.

**Comment by treeder** [comment]
I just don't see why that's even in this library at all, or full react itself which is hard linked, not sure what that has to do with sending emails.
