### ISSUE TITLE
Bundler error in Cloudflare Workers: Cannot resolve "@react-email/render" when using resend.emails.send with html only (React not used)

### ISSUE THREAD

**Issue by nexckycort** [resend/resend-node#587]
### Describe the Bug

I'm experiencing a bundling error when deploying to Cloudflare Workers using Wrangler v4.32.0. Even though I’m only sending HTML emails via the `html` prop (without any React component), the build fails with:

```
ERROR: Could not resolve "@react-email/render"
```

This happens despite using the latest `resend` version (v6.0.1). If I downgrade `resend` to an older version (4.8.0), the error disappears.

### Link to the code that reproduces this issue

https://github.com/resend

### To Reproduce

**Steps to Reproduce**

1. Install latest `resend` (e.g., `resend@6.0.1`).
2. In a Cloudflare Worker, call:

   ```js
   await resend.emails.send({
     from: "noreply@...com",
     to: email,
     subject: `...`,
     html: "<div>Some HTML</div>",
   });
   ```
3. Run `wrangler deploy` — even without using `react` at all — results in:

   ```
   ERROR: Could not resolve "@react-email/render"
   ```

### Expected Behavior

The Worker should bundle and deploy successfully when using plain HTML only.

**Comment by jayanratna** [comment]
I believe installing `@react-email/render` will fix this issue for you. `npm install @react-email/render` :)

**Comment by gabrielmfern** [comment]
Couldn't reproduce with our [Cloudflare Workers example](https://github.com/resend/resend-cloudflare-workers-example), even after updating to wrangler@4.32.0 and removing `@react-email` completely.

Can you please share a reproduction for this?

**Comment by gabrielmfern** [comment]
Was able to reproduce this when bundling with esbuild, seems like it happens because the bundler tries to bundle in `@react-email/render`. Workaround is to just set `@react-email/render` as external

**Comment by astanciu** [comment]
Having the same issue. @gabrielmfern where did you set it as external?

**Comment by gabrielmfern** [comment]
@astanciu I'm afraid there's no external for the `wrangler` CLI, this only works when doing bundling yourself, or using something more customizable. The simplest thing you can do, *for Cloudflare Workers*, is installing `@react-email/render` so that the error goes away.

**Comment by chakravarthi-bb** [comment]
> Couldn't reproduce with our [Cloudflare Workers example](https://github.com/resend/resend-cloudflare-workers-example?rgh-link-date=2025-08-22T12%3A24%3A16.000Z), even after updating to wrangler@4.32.0 and removing `@react-email` completely.
> 
> Can you please share a reproduction for this?

Why would you add package that's not needed for your repo?

Facing same issue with docker builds where it requires react email, whereas I only need html

**Comment by emiliosheinz** [comment]
Just a heads-up. I opened a discussion about this issue [here](https://github.com/resend/resend-node/discussions/588). You might be interested in taking a look and sharing your thoughts.

**Comment by gabrielmfern** [comment]
> Why would you add package that's not needed for your repo?

@chakravarthi-bb it's not added, we just support it conditionally, and it only gets truly imported when the `react` prop is present. The problem is that esbuild (the cloudflare bundler) tries to bundle in those dynamic imports as well, which causes the errors

**Comment by gabrielmfern** [comment]
Since Cloudflare Workers uses esbuild, seems like we can rely on the heuristics it uses https://github.com/evanw/esbuild/issues/3216#issuecomment-1628913722 and things should work. Will look into this soon.

You want to try this out @emiliosheinz?

**Comment by emiliosheinz** [comment]
Sorry @gabrielmfern, I had a busy week and didn't have time to look into it. But seems like you have already figured it out. Let me know if I can help with anything else.

**Comment by Akryum** [comment]
> But seems like you have already figured it out.

Has a fix been released somewhere?

**Comment by gabrielmfern** [comment]
@Akryum not yet, sorry

**Comment by merhmerh** [comment]
Im using it inside my sveltekit app. I updated the package and I encounter this issues as well.
I couldn't managed to figured out how to set as external, my solution is to use v4.x which does not have react in it. 
Hopefully resend team can work this out. Not everyone need react to send email 😂

**Comment by BlueBazze** [comment]
You have a block of code that takes up about 1kb when transpiled. Which is forced into your customers builds when using your official sdk.
This one KB is only used by your customers that use React, and not even all your customers may be using this feature.
But this is included in every build, every build transfer. But no worries, your customer pays for this.

All that to save your react customers from importing this package and calling the function.

This is not even the first time this specific issue has been raised in this repo https://github.com/resend/resend-node/issues/309.
Now you have spent 3 weeks internally discussing decoupling the react part.

Almost two years you have had issues with react-email in the sdk.
How many man hours has it cost you to save your react customers from two lines of code?

**Comment by gabrielmfern** [comment]
@BlueBazze you're definitely right, we should've coordinated internally much faster and should've had this not be the case from the start. Very sorry that you all have had to deal with this all of this time.

I've just made #620 which should fix the issues with Cloudflare Workers/esbuild. If anyone's blocked, feel free to use the preview version:

```zig
npm i https://pkg.pr.new/resend/resend-node/resend@620
```

**Comment by gabrielmfern** [comment]
Should be fixed in [resend@6.1.0](https://github.com/resend/resend-node/releases/tag/v6.1.0)!

**Comment by edwardrpool** [comment]
I'm still having this issue as of v6.1.0. Never had the issue beforehand. I am running the app locally and if my page calls for Resend I get the error Module not found: Can't resolve '@react-email/render'

I see the '@react-email/render' listed as optional in the package-lock.json, but find it odd to have to import it directly if it's required by the parent package.

**Comment by gabrielmfern** [comment]
Hey @edwardrpool, the original issue when deploying with Cloudflare Workers is fixed, you might be having another situation with the same error. Can you share a reproduction, and maybe create another issue?

**Comment by nsina** [comment]
Can confirm that this issue still persist in [v.6.1.0](https://github.com/resend/resend-node/releases/tag/v6.1.0) running a Nuxt project on Cloudflare Workers.

```
13:47:42.118 | [error] [nitro] Error: Cannot resolve "@react-email/render" from "/opt/buildhome/repo/node_modules/.pnpm/resend@6.1.0/node_modules/resend/dist/index.mjs" and externals are not allowed!
13:47:42.119 | [error] Cannot resolve "@react-email/render" from "/opt/buildhome/repo/node_modules/.pnpm/resend@6.1.0/node_modules/resend/dist/index.mjs" and externals are not allowed!
13:47:42.119 | at Object.resolveId (node_modules/.pnpm/nitropack@2.12.6_better-sqlite3@12.2.0/node_modules/nitropack/dist/rollup/index.mjs:2010:17)
13:47:42.120 | at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
13:47:42.120 | at async resolveId (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
13:47:42.120 | at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
13:47:42.120 | at async Object.resolveId (node_modules/.pnpm/@rollup+plugin-commonjs@28.0.6_rollup@4.50.2/node_modules/@rollup/plugin-commonjs/dist/es/index.js:604:10)
13:47:42.120 | at async PluginDriver.hookFirstAndGetPlugin (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:22310:28)
13:47:42.120 | at async resolveId (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:20787:26)
13:47:42.120 | at async ModuleLoader.resolveId (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21223:15)
13:47:42.120 | at async ModuleLoader.resolveDynamicImport (node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21627:82)
13:47:42.121 | at async node_modules/.pnpm/rollup@4.50.2/node_modules/rollup/dist/es/shared/node-entry.js:21511:32
13:47:42.121 |  
13:47:42.121 | [error] Cannot resolve "@react-email/render" from "/opt/buildhome/repo/node_modules/.pnpm/resend@6.1.0/node_modules/resend/dist/index.mjs" and externals are not allowed!
```

**Comment by krisnaw** [comment]
This issue also appears on a fresh install of Next.js, running Resend v6.1.0, on local development.
